# Generated by Django 4.2.7 on 2023-11-07 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='website.order'),
        ),
    ]
